# .github/workflows/deploy.yml
name: Deploy PR previews
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize    
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # Checkout the branch associated with the PR
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source-dir: .
          umbrella-dir: pr-preview
          action: auto