# .github/workflows/deploy.yml
name: Deploy PR previews
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize    
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Build
        if: github.event.action != 'closed' # You might want to skip the build if the PR has been closed
        run: |
          npm install
          npm run build
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          preview-branch: main
          source-dir: dist
          umbrella-dir: pr-preview
          action: auto